name: iStasis
favicon: null
layout_spectrum: 0.74594
typography_spectrum: 0.25204
title: iStasis Blog
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-15959524-3
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#cecece'
    - '#232323'
    - '#5a7646'
    - '#d77b18'
  brandStrength: 1
  lightness: 0
  saturation: 0.5
  rhythmicContrast: 0
purpose: []
