title: iStasis Blog
purpose: []
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0.2530669
  brandStrength: 0.7759082
  lightness: 0.9296439
  brandColors:
    - '#000000'
    - '#A3A3A3'
    - '#FCFCFC'
    - '#424242'
  rhythmicContrast: 0.5117476
cta:
  bucket: null
  version: null
  domain: null
analytics:
  twitter: null
  google: UA-15959524-3
  facebook: null
favicon: null
name: iStasis
opengraph:
  image: null
  type: null
  appId: null
typography_spectrum: 0.158696
layout_spectrum: 1
